---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vpn
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "vpn",
      "plugins": [
        {
          "type": "macvlan",
          "master": "bond0.90",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              {"dst": "0.0.0.0/5", "gw": "192.168.90.1"},
              {"dst": "8.0.0.0/7", "gw": "192.168.90.1"},
              {"dst": "11.0.0.0/8", "gw": "192.168.90.1"},
              {"dst": "12.0.0.0/6", "gw": "192.168.90.1"},
              {"dst": "16.0.0.0/4", "gw": "192.168.90.1"},
              {"dst": "32.0.0.0/3", "gw": "192.168.90.1"},
              {"dst": "64.0.0.0/2", "gw": "192.168.90.1"},
              {"dst": "128.0.0.0/1", "gw": "192.168.90.1"}
            ]
          }
        }
      ]
    }
